# fly.toml app configuration file generated for orbitask-manager on 2025-09-18T17:31:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'orbitask-manager'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 5020
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
